// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Account struct {
	AccountNo      int32
	StudentNo      string
	HashedPassword string
}

type Student struct {
	StudentNo         string
	Balance           float64
	DailyPaymentLimit int32
}

type Tuition struct {
	TuitionID    int32
	StudentNo    string
	Term         string
	TuitionTotal float64
}
