// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addNewStudent = `-- name: AddNewStudent :exec
INSERT INTO student(student_no,balance)
VALUES ($1,$2)
RETURNING student_no
`

type AddNewStudentParams struct {
	StudentNo string
	Balance   float64
}

func (q *Queries) AddNewStudent(ctx context.Context, arg AddNewStudentParams) error {
	_, err := q.db.Exec(ctx, addNewStudent, arg.StudentNo, arg.Balance)
	return err
}

const addStudentAccount = `-- name: AddStudentAccount :exec
INSERT INTO account(student_no,hashed_password)
VALUES ($1,$2)
`

type AddStudentAccountParams struct {
	StudentNo      string
	HashedPassword string
}

func (q *Queries) AddStudentAccount(ctx context.Context, arg AddStudentAccountParams) error {
	_, err := q.db.Exec(ctx, addStudentAccount, arg.StudentNo, arg.HashedPassword)
	return err
}

const addTuitionToOneStudent = `-- name: AddTuitionToOneStudent :exec
INSERT INTO tuition(student_no,term,tuition_total)
VALUES ($1,$2,$3)
`

type AddTuitionToOneStudentParams struct {
	StudentNo    string
	Term         string
	TuitionTotal float64
}

func (q *Queries) AddTuitionToOneStudent(ctx context.Context, arg AddTuitionToOneStudentParams) error {
	_, err := q.db.Exec(ctx, addTuitionToOneStudent, arg.StudentNo, arg.Term, arg.TuitionTotal)
	return err
}

const decreasePaymentLimit = `-- name: DecreasePaymentLimit :exec
UPDATE student
SET daily_payment_limit = daily_payment_limit-1
WHERE student_no = $1
`

func (q *Queries) DecreasePaymentLimit(ctx context.Context, studentNo string) error {
	_, err := q.db.Exec(ctx, decreasePaymentLimit, studentNo)
	return err
}

const getAccountByStudentNo = `-- name: GetAccountByStudentNo :one
SELECT account_no, student_no, hashed_password FROM account
WHERE student_no = $1
`

func (q *Queries) GetAccountByStudentNo(ctx context.Context, studentNo string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByStudentNo, studentNo)
	var i Account
	err := row.Scan(&i.AccountNo, &i.StudentNo, &i.HashedPassword)
	return i, err
}

const getStudentById = `-- name: GetStudentById :one
SELECT student.student_no, balance, daily_payment_limit, tuition_id, tuition.student_no, term, tuition_total FROM student
LEFT JOIN tuition
ON student.student_no = tuition.student_no
WHERE student.student_no = $1
`

type GetStudentByIdRow struct {
	StudentNo         string
	Balance           float64
	DailyPaymentLimit int32
	TuitionID         pgtype.Int4
	StudentNo_2       pgtype.Text
	Term              pgtype.Text
	TuitionTotal      pgtype.Float8
}

func (q *Queries) GetStudentById(ctx context.Context, studentNo string) (GetStudentByIdRow, error) {
	row := q.db.QueryRow(ctx, getStudentById, studentNo)
	var i GetStudentByIdRow
	err := row.Scan(
		&i.StudentNo,
		&i.Balance,
		&i.DailyPaymentLimit,
		&i.TuitionID,
		&i.StudentNo_2,
		&i.Term,
		&i.TuitionTotal,
	)
	return i, err
}

const getStudentDailyLimit = `-- name: GetStudentDailyLimit :one
SELECT daily_payment_limit 
FROM student
WHERE student_no = $1
`

func (q *Queries) GetStudentDailyLimit(ctx context.Context, studentNo string) (int32, error) {
	row := q.db.QueryRow(ctx, getStudentDailyLimit, studentNo)
	var daily_payment_limit int32
	err := row.Scan(&daily_payment_limit)
	return daily_payment_limit, err
}

const getTuitionByTerm = `-- name: GetTuitionByTerm :many
SELECT student.student_no, balance, daily_payment_limit, tuition_id, tuition.student_no, term, tuition_total FROM student
INNER JOIN tuition
ON student.student_no = tuition.student_no
WHERE student.student_no = $1
AND tuition.term = $2
`

type GetTuitionByTermParams struct {
	StudentNo string
	Term      string
}

type GetTuitionByTermRow struct {
	StudentNo         string
	Balance           float64
	DailyPaymentLimit int32
	TuitionID         int32
	StudentNo_2       string
	Term              string
	TuitionTotal      float64
}

func (q *Queries) GetTuitionByTerm(ctx context.Context, arg GetTuitionByTermParams) ([]GetTuitionByTermRow, error) {
	rows, err := q.db.Query(ctx, getTuitionByTerm, arg.StudentNo, arg.Term)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTuitionByTermRow
	for rows.Next() {
		var i GetTuitionByTermRow
		if err := rows.Scan(
			&i.StudentNo,
			&i.Balance,
			&i.DailyPaymentLimit,
			&i.TuitionID,
			&i.StudentNo_2,
			&i.Term,
			&i.TuitionTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetTuitionTotal = `-- name: ResetTuitionTotal :exec
UPDATE tuition
SET tuition_total = 0
WHERE student_no = $1 
AND term = $2
`

type ResetTuitionTotalParams struct {
	StudentNo string
	Term      string
}

func (q *Queries) ResetTuitionTotal(ctx context.Context, arg ResetTuitionTotalParams) error {
	_, err := q.db.Exec(ctx, resetTuitionTotal, arg.StudentNo, arg.Term)
	return err
}

const unpaidTuitions = `-- name: UnpaidTuitions :many
SELECT student.student_no, balance, daily_payment_limit, tuition_id, tuition.student_no, term, tuition_total
FROM student
INNER JOIN tuition
ON student.student_no = tuition.student_no
WHERE tuition.tuition_total > 0
LIMIT $1 OFFSET $2
`

type UnpaidTuitionsParams struct {
	Limit  int32
	Offset int32
}

type UnpaidTuitionsRow struct {
	StudentNo         string
	Balance           float64
	DailyPaymentLimit int32
	TuitionID         int32
	StudentNo_2       string
	Term              string
	TuitionTotal      float64
}

func (q *Queries) UnpaidTuitions(ctx context.Context, arg UnpaidTuitionsParams) ([]UnpaidTuitionsRow, error) {
	rows, err := q.db.Query(ctx, unpaidTuitions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnpaidTuitionsRow
	for rows.Next() {
		var i UnpaidTuitionsRow
		if err := rows.Scan(
			&i.StudentNo,
			&i.Balance,
			&i.DailyPaymentLimit,
			&i.TuitionID,
			&i.StudentNo_2,
			&i.Term,
			&i.TuitionTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE student
SET balance = $2
WHERE student_no = $1
`

type UpdateBalanceParams struct {
	StudentNo string
	Balance   float64
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBalance, arg.StudentNo, arg.Balance)
	return err
}
